### ISSUE TITLE
Prevent logging of error messages on not existing link targets

### ISSUE THREAD

**Issue by serialcool** [aperto/magnolia-vanity-url#16]
The SessionUtil from Magnolia logs ERRORs if the node identifier doesn't exists. A previous check would prevent such messages.

> 19-11-25 12:06:10 ERROR suapp509[http-nio-8081-exec-9]info.magnolia.jcr.util.SessionUtil: Exception trying to access node with identifier: '9be65aec-cad9-4392-b617-83c14eaa0e9d' in workspace: 'website'
javax.jcr.ItemNotFoundException: 9be65aec-cad9-4392-b617-83c14eaa0e9d
	at org.apache.jackrabbit.core.ItemManager.getItemData(ItemManager.java:384) ~[jackrabbit-core-2.16.1.jar:2.16.1]
	at org.apache.jackrabbit.core.ItemManager.getItem(ItemManager.java:328) ~[jackrabbit-core-2.16.1.jar:2.16.1]
	at org.apache.jackrabbit.core.ItemManager.getItem(ItemManager.java:621) ~[jackrabbit-core-2.16.1.jar:2.16.1]
	at org.apache.jackrabbit.core.SessionImpl.getNodeById(SessionImpl.java:538) ~[jackrabbit-core-2.16.1.jar:2.16.1]
	at org.apache.jackrabbit.core.SessionImpl.getNodeByIdentifier(SessionImpl.java:1142) ~[jackrabbit-core-2.16.1.jar:2.16.1]
	at info.magnolia.jcr.wrapper.DelegateSessionWrapper.getNodeByIdentifier(DelegateSessionWrapper.java:182) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.wrapper.DelegateSessionWrapper.getNodeByIdentifier(DelegateSessionWrapper.java:182) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.decoration.ContentDecoratorSessionWrapper.getNodeByIdentifier(ContentDecoratorSessionWrapper.java:129) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.wrapper.DelegateSessionWrapper.getNodeByIdentifier(DelegateSessionWrapper.java:182) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.decoration.ContentDecoratorSessionWrapper.getNodeByIdentifier(ContentDecoratorSessionWrapper.java:129) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.wrapper.DelegateSessionWrapper.getNodeByIdentifier(DelegateSessionWrapper.java:182) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.decoration.ContentDecoratorSessionWrapper.getNodeByIdentifier(ContentDecoratorSessionWrapper.java:129) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.wrapper.DelegateSessionWrapper.getNodeByIdentifier(DelegateSessionWrapper.java:182) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.decoration.ContentDecoratorSessionWrapper.getNodeByIdentifier(ContentDecoratorSessionWrapper.java:129) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.wrapper.DelegateSessionWrapper.getNodeByIdentifier(DelegateSessionWrapper.java:182) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.decoration.ContentDecoratorSessionWrapper.getNodeByIdentifier(ContentDecoratorSessionWrapper.java:129) ~[magnolia-core-5.7.2.jar:?]
	at info.magnolia.jcr.util.SessionUtil.getNodeByIdentifier(SessionUtil.java:128) [magnolia-core-5.7.2.jar:?]
	at com.aperto.magnolia.vanity.DefaultPublicUrlService.getExternalLinkFromId(DefaultPublicUrlService.java:127) [magnolia-vanity-url-1.5.2.jar:?]
	at com.aperto.magnolia.vanity.DefaultPublicUrlService.createTargetUrl(DefaultPublicUrlService.java:114) [magnolia-vanity-url-1.5.2.jar:?]
	at com.aperto.magnolia.vanity.VanityUrlService.createPublicUrl(VanityUrlService.java:120) [magnolia-vanity-url-1.5.2.jar:?]

**Comment by serialcool** [comment]
SessionUtil is not used anymore for node retrieval.
